CREATE TABLE usuario (
   id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   nombre_usuario VARCHAR2(100) UNIQUE NOT NULL,
   clave VARCHAR2(200) NOT NULL, -- hash
   nombre VARCHAR2(100),
   apellido VARCHAR2(100),
   fecha_nacimiento DATE,
   telefono VARCHAR2(20),
   email VARCHAR2(150),
   tipo VARCHAR2(20) -- 'paciente','medico','admin'
);
